name: Githab action
run-name: Building and push two images
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Download project
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Build and push tomcat
        uses: docker/build-push-action@v3
        with:
          context: tomcat/
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tomcat:${{github.sha}}
          file: tomcat/Dockerfile
      -
        name: Build and push nginx
        uses: docker/build-push-action@v3
        with:
          context: loadBalancer/
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/nginx:${{github.sha}}
          file: loadBalancer/Dockerfile
